# Generated by Django 5.1.3 on 2024-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_from', models.CharField(max_length=3)),
                ('code_to', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=8)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
