# Generated by Django 5.1.3 on 2024-12-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_exchangerate_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
